### ISSUE TITLE
RuntimeError: NaN loss!

### ISSUE THREAD

**Issue by kansalaman** [yairf11/MUPPET#2]
While training the encoder i.e

`python hotpot/scripts/train_eval/ablate_iterative_hotpot.py <model name> --label-method br-as-cp --rank`

After the model has trained for 36 epochs, I get the following traceback -

`Traceback (most recent call last):
  File "hotpot/scripts/train_eval/ablate_iterative_hotpot.py", line 346, in <module>
    main()
  File "hotpot/scripts/train_eval/ablate_iterative_hotpot.py", line 335, in main
    trainer.start_training(data, model, params, eval, model_dir.ModelDir(out), notes, save_graph=False)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/trainer.py", line 451, in start_training
    True, train_params, evaluators, out, notes, dry_run, save_graph=save_graph)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/trainer.py", line 528, in _train
    evaluators, out, notes, dry_run, start_eval, save_graph=save_graph)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/trainer.py", line 824, in _train_async
    raise RuntimeError("NaN loss!")
RuntimeError: NaN loss!`

@yairf11 can you please tell whether this was the same in your case or the encoder trained fine till 80 epochs? If the latter what might be the reason since I did not change the source code even a bit? Also it'll be really helpful if you could provide with pre-trained checkpoints

Thanks in advance!

**Comment by yairf11** [comment]
Hi!
I don't recall having this problem when training with the hyper-parameters that are currently in the training script. However, it is possible that lowering the learning rate will help. Keep me updated if that solves the problem for you. 
Regarding the pre-trained checkpoints - I will try to upload them as soon as I can, thanks for reminding me to do it 😊

**Comment by yairf11** [comment]
Hi, the pretrained models are available here: https://github.com/yairf11/MUPPET/blob/master/README.md#pretrained-models

**Comment by kansalaman** [comment]
Thanks @yairf11  for the pretrained models. Lowering the learning rate indeed helped solve NaN loss problem. There's one more error I am getting.
While running the command -
`python hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py <qa model dir> qa_pred.json -s latest -c retrieval_file -t 600 --input_file <out dir>/n2-64/n1-32/n1-32_n2-64_k1-8_k2-45.json --test_mode`

I get the following error log. I tried this after doing training myself as well as using the pretrained models -
```
Using DB documents
7405it [00:03, 2382.36it/s]█████████████████████████████████████████████████████████████████████████████▊           | 6588/7405 [00:03<00:02, 343.65it/s]
Tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 7405/7405 [00:03<00:00, 2380.34it/s]
166070it [01:40, 1646.28it/s]█████████████████████████████████████████████████████████████████████████████████▉| 166044/166070 [01:40<00:00, 1882.35it/s]
Tokenize: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 166070/166070 [01:40<00:00, 1646.20it/s]
Setting up model
Had pre-trained word embeddings for 331543 of 511556 words
2020-05-23 23:05:17.351057: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-23 23:05:18.158349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:81:00.0
totalMemory: 11.91GiB freeMemory: 9.38GiB
2020-05-23 23:05:18.158414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2020-05-23 23:05:18.752609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-23 23:05:18.752759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0
2020-05-23 23:05:18.752815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N
2020-05-23 23:05:18.768291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9071 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:81:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1589, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 2 but is 1 for 'unstack_4' (op: 'Unpack') with input shapes: [?,1,?,400].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py", line 514, in <module>
    main()
  File "hotpot/scripts/train_eval/hotpot_qa_distractors_eval.py", line 475, in main   
    loader, checkpoint, not args.no_ema, 10)[args.corpus]
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/trainer.py", line 895, in test
    pred = model.get_predictions_for(input_dict)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/models/multiple_context_models.py", line 241, in get_predictions_for
    sentence_segments=sentence_segments, sentence_mask=sentence_mask)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/hotpot/models/iterative_context_models.py", line 226, in _get_predictions_for
    context1_rep, context2_rep = tf.unstack(context_rep, axis=1, num=2)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1016, in unstack
    return gen_array_ops.unpack(value, num=num, axis=axis, name=name)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9138, in unpack
    "Unpack", value=value, num=num, axis=axis, name=name)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1756, in __init__
    control_input_ops)
  File "/mnt/cherry/data/amankansal/QA/2020-Hotpot-QA/MUPPET/muppet_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1592, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension must be 2 but is 1 for 'unstack_4' (op: 'Unpack') with input shapes: [?,1,?,400].
```
Any ideas why this seems to be happening?

**Comment by yairf11** [comment]
I don't think I've encountered this error when running this script. I have also run this script again with the pre-trained model I supplied just to make sure, but didn't run into problems. Just guessing, but maybe something to do with the environment? Is your TF version 1.9?
